### ISSUE TITLE
Set up partition utility

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-os#4]
Set up disk partitioning utility inside the image.

## Subtasks

- [x] Have a working script (maybe make ***/media/noma*** if we are using noma or have it set to ***/mnt/ssd***)
- [x] Test it out on /etc/init.d/ with start command
- [x] Symlink it to /etc/rc2.d and test it out on reboot

### Expected Result

EXT4 partition created

**Comment by nolim1t** [comment]
Some commands specific to raspbian (debian) to check

```
df -h | awk '$1=="/dev/root"{print $2}'
```

Or we can salvage some stuff from the pi-factory project too.

First partition is always /dev/sda so we should check existance of it

**Comment by nolim1t** [comment]
Another helpful tool

**Comment by nolim1t** [comment]
# Detect Partition size

From the [lncm usb sizer](https://github.com/lncm/pi-factory/blob/v0.4.1/usr/local/sbin/lncm-usb.py)

```python
#!/usr/bin/env python3

import os
import sys
import glob
import re

def dev_size(device):
    path = '/sys/block/'
    num_sectors = open(path + device + '/size').read().rstrip('\n')
    sector_size = open(path + device + '/queue/hw_sector_size').read().rstrip('\n')
    return (int(num_sectors)*int(sector_size))

def main():
    print('USB')
    print('Size: ' + str(dev_size('sda') / (1000*1000)))

if __name__ == '__main__':
    main()
```
